# Site settings
title: Gautam Chandra, Technology Enthusiast, RoR Consultant, Full Stack Developer
tag_text: Myself
description: About Me.

# Build settings
markdown: kramdown

exclude: ["README.md"]
