# Site settings
title: Gautam Chandra, Technology Enthusiast, RoR Consultant, Full Stack Developer
tag_text: "Hello, I'm Gautam Chandra"
description: About Me.

# Build settings
markdown: kramdown

exclude: ["README.md"]
